load("@rules_java//java:defs.bzl", "java_library")

package(
    default_visibility = ["//visibility:public"],
)

java_library(
    name = "junit5-jupiter-starter-bazel",
    srcs = ["Calculator.java"],
)
